# azure-pipelines/templates/ci-python.yml
parameters:
  - name: pythonVersion
    type: string
    default: '3.11'

jobs:
- job: BuildAndTestPython
  displayName: "Python Build & Test"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.pythonVersion }}
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: "Install dependencies"
    - script: |
        pytest
      displayName: "Run tests"
