# azure-pipelines/templates/ci-java.yml
parameters:
  - name: javaVersion
    type: string
    default: '17'

jobs:
- job: BuildAndTestJava
  displayName: "Java Build & Test"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: ${{ parameters.javaVersion }}
        jdkArchitectureOption: 'x64'
    - script: |
        ./gradlew build
      displayName: "Build project"
    - script: |
        ./gradlew test
      displayName: "Run tests"
